# Generated by Django 5.1.4 on 2026-07-19 08:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('started_on', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_on', '-id'),
            },
        ),
        migrations.CreateModel(
            name='InvestmentProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_kind', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly')], default='monthly', max_length=10)),
                ('period_start', models.DateField()),
                ('amount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profits', to='investments.investment')),
            ],
            options={
                'ordering': ('-period_start', '-id'),
                'constraints': [models.UniqueConstraint(fields=('investment', 'period_kind', 'period_start'), name='investments_profit_unique_period')],
            },
        ),
    ]
