# Generated by Django 5.1.4 on 2026-07-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancemovement',
            name='kind',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('adjustment', 'Adjustment'), ('expense', 'Expense'), ('receipt', 'Receipt from settlement'), ('payout', 'Payout to person'), ('investment', 'Investment')], max_length=20),
        ),
    ]
