# Generated by Django 5.1.4 on 2026-07-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_balancemovement_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_investment_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='default_investment_rate_mode',
            field=models.CharField(choices=[('annual', 'Annual %'), ('monthly', 'Monthly %')], default='annual', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='default_investment_rate_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='default_investment_started_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balancemovement',
            name='kind',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('adjustment', 'Adjustment'), ('expense', 'Expense'), ('receipt', 'Receipt from settlement'), ('payout', 'Payout to person'), ('investment', 'Investment'), ('default_profit', 'Default investment profit')], max_length=20),
        ),
    ]
